export const APPS_CALL_BEGIN = "APPS_CALL_BEGIN";
export const APPS_CALL_COMPLETE = "APPS_CALL_COMPLETE";
export const APPS_WRITE_DATA = "APPS_WRITE_DATA";

export const LOGS_CLEAR_DATA = "LOGS_CLEAR_DATA";
export const LOGS_API_CALL_BEGIN = "LOGS_API_CALL_BEGIN";
export const LOGS_API_CALL_COMPLETE = "LOGS_API_CALL_COMPLETE";
export const LOGS_WRITE_DATA = "LOGS_WRITE_DATA";

export const QUERY_SET_SELECTED_APP = "QUERY_SET_SELECTED_APP";
export const QUERY_SET_DATE_START = "QUERY_SET_DATE_START";
export const QUERY_SET_DATE_END = "QUERY_SET_DATE_END";

export const SORT_SET_SORT_ORDER = "SORT_SET_SORT_ORDER";
