export const QUERY_SET_DATE_START = "QUERY_SET_DATE_START";
export const QUERY_SET_DATE_END = "QUERY_SET_DATE_END";

export const LOGS_START_LOADING = "LOGS_START_LOADING";
export const LOGS_APP_DATA_LOADED = "LOGS_APP_DATA_LOADED";

export const SORT_SET_SORT_ORDER = "SORT_SET_SORT_ORDER";
